### PR TITLE
avoid fetching in context processor

### PR DESCRIPTION
**Pull request by miltontony**

### CODE REVIEW

**Comment by miltontony** [comment]
@smn ready for review?

**Comment by miltontony** [comment]
This has been causing [this error](http://prd-sentry.za.prk-host.net/unicore/django-cms-prod/group/44663/)

**Comment by smn** [comment]
Is it possible to get a failing test?

**Comment by smn** [comment]
:+1: anyway

**Comment by miltontony** [comment]
@smn I've received some reports that after removing the `fetch` in the context processor, the link that allows you to publish changes doesn't consistently show. Perhaps we should keep it and just put it in a try block

**Pull request merged**
