### PR TITLE
set Page and Category image fields in import_from_git command

### PR DESCRIPTION
**Pull request by Rizziepit**

### CODE REVIEW

**Comment by Rizziepit** [comment]
@miltontony ready for review

**Comment by Rizziepit** [comment]
I'm now only re-uploading images when they're not on the same Thumbor server

**Comment by miltontony** [comment]
I think we need to do a `push` now since we've committed some new stuff.

**Comment by miltontony** [comment]
otherwise :+1:

**Comment by Rizziepit** [comment]
@miltontony pushing to git now https://github.com/universalcore/unicore-cms-django/commit/8d9376d557937b94400cced1bb859a90bbd5ff3d

**Comment by miltontony** [comment]
:+1:

**Pull request merged**
