### PR TITLE
CMS automatically duplicates linking to related posts

### PR DESCRIPTION
**Pull request by smn**
Issue raised by Sarah:
"If I link article A to article B the system automatically links B back to A as well.
So any post that I linked to 'Your New Baby' will then also have a link from 'Your New Baby' to it. This is not ideal as I linked many posts to this particular post (for example) but don't want to link from this post to all those articles. "

This was originally filed under https://github.com/praekelt/unicore-cms/issues/42

### CODE REVIEW

**Comment by smn** [comment]
@miltontony ready for review

**Comment by SteveBarnett** [comment]
@smn But sometimes you _would_ want that? Would it make sense to have a 
- [x] Also link article B to this article

option or similar?
Can we ask Sarah?

**Comment by miltontony** [comment]
@smn we also need to ensure it doesn't get written to json. Test?

**Comment by smn** [comment]
It would definitely, but currently here we're bound by Django's Admin's rules which do not allow for that. We need to keep a list of these ideas for the _real_ admin we're going to have to design because this is one to throw away in every sense of the word.

**Comment by smn** [comment]
@miltontony thanks, writing test.

**Comment by miltontony** [comment]
:+1:

**Comment by smn** [comment]
@tsepot please test

**Pull request merged**
