### PR TITLE
Add support for tagging

### PR DESCRIPTION
**Pull request by smn**
These tags are meant for authors, not users.

### CODE REVIEW

**Comment by smn** [comment]
not ready for review yet, blocked by https://github.com/universalcore/elastic-git/issues/12.

**Comment by smn** [comment]
@miltontony ready for review

**Comment by miltontony** [comment]
@smn Please add tags to `import_from_git`

**Comment by smn** [comment]
@miltontony thanks, ready for re-review

**Comment by smn** [comment]
Thumbor's latest release fails to install on Travis as a package, filed https://github.com/thumbor/thumbor/issues/391.

**Comment by miltontony** [comment]
:+1:

**Pull request merged**
