### PR TITLE
add ordering for pages

### PR DESCRIPTION
**Pull request by miltontony**
Reported by Sarah in [UNICORE-36](https://praekelt.atlassian.net/browse/UNICORE-36)

### CODE REVIEW

**Comment by miltontony** [comment]
@smn ready for review

**Comment by miltontony** [comment]
@smn I've added [universalcore #40 - Make language a required field](https://github.com/universalcore/unicore/issues/40) here as well

**Comment by smn** [comment]
:+1:

**Comment by miltontony** [comment]
@smn just 1 more thing here

**Comment by smn** [comment]
:+1: again

**Pull request merged**
